package: media_negotiator
version: 2.1.0
name: Media Negotiator
author: Andreas Lenhardt

requires:
    redaxo: ^5.13.0
    php:
        version: "^8.0"
    packages:
        media_manager: '^2.11.0'
