package: media_negotiator
version: 2.2.2
name: Media Negotiator
author: Andreas Lenhardt
supportpage: https://github.com/AndiLeni/media_negotiator

page:
    title: 'Media Negotiator'
    perm: media_negotiator[]
    subpages:
            config:
                { title: 'Einstellungen', icon: rex-icon fa-cog }    
    
default_config:
    force_imagick: false

requires:
    redaxo: ^5.13.0
    php:
        version: "^8.0"
    packages:
        media_manager: '^2.11.0'
