package: media_negotiator
version: 2.2.1
name: Media Negotiator
author: Andreas Lenhardt
supportpage: https://github.com/AndiLeni/media_negotiator

page:
    title: 'Media Negotiator'
    icon: 'maintenance rex-icon fa-pie-chart'
    perm: media_negotiator[]
    subpages:
            config:
                { title: 'Config', icon: rex-icon fa-laptop }    
    
default_config:
    force_imagick: false
    frontend: 

requires:
    redaxo: ^5.13.0
    php:
        version: "^8.0"
    packages:
        media_manager: '^2.11.0'
